Repository knative-extensions/kperf, pull requests merged in 2020-12, with the labels that each got.

#21 Refine serving and networking client initialization
  go.mod
  go.sum
  pkg/command/service/clean.go
  pkg/command/service/generate.go
  pkg/command/service/measure.go
  pkg/command/utils/htmltemplatebindata.go
  pkg/generator/batch_cleaner.go
  pkg/generator/batch_generator.go
  pkg/types.go
Labels: approved, cla: yes, lgtm, size/XL

#11 As a Kperf developer, I want to refine service generate/measure flags code comments and etc
  README.md
  go.mod
  go.sum
  pkg/command/service/clean.go
  pkg/command/service/common.go
  pkg/command/service/generate.go
  pkg/command/service/measure.go
  pkg/command/utils/htmltemplatebindata.go
  pkg/generator/batch_cleaner.go
  pkg/generator/batch_generator.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#22 add unit test for generator
  go.mod
  go.sum
  hack/build-funcs.sh
  pkg/command/utils/htmltemplatebindata.go
  pkg/generator/batch_cleaner.go
  pkg/generator/batch_cleaner_test.go
  pkg/generator/batch_generator.go
  pkg/generator/batch_generator_exit_test.go
  pkg/generator/batch_generator_test.go
Labels: approved, cla: yes, lgtm, size/L

#25 add measure result
  pkg/command/service/common.go
  pkg/command/service/measure.go
  pkg/generator/batch_generator.go
Labels: approved, cla: yes, lgtm, size/L

#23 Refined test namespace check and readme
  .gitignore
  README.md
  docs/service_creation.png
  go.mod
  pkg/command/service/generate.go
Labels: approved, cla: yes, kind/bug, kind/documentation, lgtm, size/L

#26 add chart description in html and readme
  README.md
  docs/kperf_dashboard.png
  pkg/command/utils/htmltemplatebindata.go
  templates/single_chart.html
Labels: approved, cla: yes, lgtm, size/L

#28 fix a small error in build script
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS
