Repository knative-extensions/kperf, pull requests merged in 2021-03, with the labels that each got.

#51 Drop dependency on pkg/errors and use stdlib instead
  go.mod
  pkg/command/service/generate.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#50 Drop copied test directory
  test/common.sh
  test/test-infra/CODE_OF_CONDUCT.md
  test/test-infra/LICENSE
  test/test-infra/README.md
  test/test-infra/e2e-tests.sh
  test/test-infra/go.mod
  test/test-infra/hack.go
  test/test-infra/infra-library.sh
  test/test-infra/library.sh
  test/test-infra/performance-tests.sh
  test/test-infra/presubmit-tests.sh
  test/test-infra/release.sh
  test/test-infra/shellcheck-presubmit.sh
Labels: approved, cla: yes, lgtm, size/XXL

#54 Fix header issue for files in third_party folder (#53)
  hack/build-funcs.sh
Labels: approved, cla: yes, lgtm, size/XS

#55 Apply and fix the most useful linters
  .golangci.yaml
  pkg/command/service/common.go
  pkg/command/service/generate.go
  pkg/command/service/measure.go
  pkg/command/utils/util_test.go
  pkg/generator/batch_cleaner.go
  pkg/generator/batch_generator.go
  pkg/generator/batch_generator_exit_test.go
Labels: approved, cla: yes, lgtm, size/L

#44 Add basic information for kperf measurement result (#35)
  pkg/command/service/measure.go
  pkg/command/service/measure_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#57 Run all actions against main
  .github/workflows/knative-go-test.yml
Labels: approved, cla: yes, lgtm, size/XS

#56 Store measurement result into a JSON file
  pkg/command/service/common.go
  pkg/command/service/measure.go
  pkg/command/utils/util.go
  pkg/command/utils/util_test.go
Labels: approved, cla: yes, lgtm, size/L

#58 Arrange public and private fields in measureResult struct
  pkg/command/service/common.go
  pkg/command/service/measure.go
Labels: approved, cla: yes, lgtm, size/L

#59 Support --output flag to specify the measure result location
  README.md
  pkg/command/service/common.go
  pkg/command/service/measure.go
  pkg/command/service/measure_test.go
  pkg/command/utils/util.go
  pkg/command/utils/util_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, ok-to-test, size/M
