Repository knative-extensions/kperf, pull requests merged in 2021-07, with the labels that each got.

#98 drop releasibility action
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/L

#99 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#97 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#100 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#101 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#102 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_autoscaling_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_metric.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/fake/fake_podautoscaler.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/metric.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/podautoscaler.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/serving_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L
