Repository knative-extensions/kperf, pull requests merged in 2021-02, with the labels that each got.

#33 add measurement for kpa and sks
  README.md
  go.mod
  go.sum
  hack/build-funcs.sh
  pkg/command/service/common.go
  pkg/command/service/measure.go
  pkg/command/service/measure_test.go
  pkg/command/utils/htmltemplatebindata.go
  pkg/types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#37 Remove whitelist terminology
  test/test-infra/README.md
Labels: approved, cla: yes, lgtm, size/XS

#38 Remove dependency to kubernetes/kubernetes
  go.mod
  pkg/command/service/measure.go
Labels: approved, cla: yes, lgtm, size/M

#41 Bump Knative and K8s dependencies
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#42 Add LICENSE file
  LICENSE
Labels: approved, cla: yes, lgtm, size/L

#46 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#45 add some UT cases for service measurement
  pkg/command/service/measure_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
