Repository knative-extensions/kperf, pull requests merged in 2021-01, with the labels that each got.

#29 Fixed incorrect license Copyright
  cmd/kperf.go
  core/root.go
  pkg/command/service/clean.go
  pkg/command/service/common.go
  pkg/command/service/generate.go
  pkg/command/service/measure.go
  pkg/command/service/service.go
  pkg/command/utils/util.go
  pkg/command/version/version.go
  pkg/generator/batch_cleaner.go
  pkg/generator/batch_cleaner_test.go
  pkg/generator/batch_generator.go
  pkg/generator/batch_generator_exit_test.go
  pkg/generator/batch_generator_test.go
  pkg/types.go
Labels: approved, cla: yes, kind/bug, lgtm, size/M

#30 Fixed incorrect license Copyright in test files
  core/root_test.go
  pkg/command/service/clean_test.go
  pkg/command/service/generate_test.go
  pkg/command/service/measure_test.go
  pkg/command/service/service_test.go
  pkg/command/utils/util_test.go
  pkg/command/version/version_test.go
  pkg/testutil/command.go
Labels: approved, cla: yes, lgtm, size/S

#31 fix typo in README.md
  README.md
Labels: approved, cla: yes, kind/documentation, lgtm, ok-to-test, size/XS
