Repository knative-extensions/kperf, pull requests merged in 2021-11, with the labels that each got.

#129 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#130 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/L, approved, lgtm

#132 Document maturity levels in sandbox
  README.md
Labels: cla: yes, size/XS, approved, lgtm

#136 Makefile to help with build and test commands
  .gitignore
  Makefile
  README.md
  hack/check-eof-newline.sh
  hack/check-language.sh
  hack/check-misspell.sh
  hack/check-trailing-whitespace.sh
  hack/install-tools.sh
Labels: cla: yes, size/L, approved, lgtm, kind/enhancement

#134 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#135 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, approved, lgtm

#137 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: cla: yes, size/L, approved, lgtm

#138 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, approved, lgtm, size/S

#133 add new sub command for service to scale and measure latency
  README.md
  pkg/command/service/clean.go
  pkg/command/service/common.go
  pkg/command/service/measure.go
  pkg/command/service/measure_test.go
  pkg/command/service/scale..go
  pkg/command/service/scale_test.go
  pkg/command/service/service.go
  pkg/types.go
Labels: cla: yes, size/XL, approved, lgtm, kind/enhancement

#140 [main] Update actions
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/XS, approved, lgtm

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#142 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#145 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: cla: yes, size/L, approved, lgtm

#143 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, approved, lgtm

#146 Fix the scale command output filename
  pkg/command/service/scale..go
Labels: cla: yes, kind/bug, approved, lgtm, size/S

#148 fix data race in scale command
  pkg/command/service/scale..go
Labels: cla: yes, kind/bug, size/XS, approved, lgtm

#149 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/modules.txt
Labels: cla: yes, size/L, approved, lgtm

#151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#152 Fix url used by scale command for checking ksvc
  pkg/command/service/scale..go
  pkg/command/service/scale_test.go
Labels: cla: yes, kind/bug, size/L, approved, lgtm
