Repository knative-extensions/kperf, pull requests merged in 2021-12, with the labels that each got.

#153 Fix scale command filename
  pkg/command/service/scale.go
Labels: cla: yes, size/XS, approved, kind/cleanup, lgtm

#154 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/M

#156 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/setupapi_windows.go
  vendor/golang.org/x/sys/windows/setupapierrors_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, approved, size/XXL, lgtm

#157 fix typo in measure command
  pkg/command/service/measure.go
Labels: kind/bug, size/XS, approved, lgtm

#158 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/bufferpool.go
  vendor/knative.dev/networking/pkg/doc.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/pkg/probe_handler.go
  vendor/knative.dev/networking/pkg/stats.go
  vendor/knative.dev/networking/pkg/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#160 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#159 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm
