Repository knative-extensions/kperf, pull requests merged in 2022-08, with the labels that each got.

#270 Update document to sync with recent updates
  README.md
  docs/examples.md
Labels: approved, kind/documentation, lgtm, size/S

#271 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#272 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#273 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#274 Support config file on service load
  docs/examples.md
  pkg/command/service/generate_test.go
  pkg/command/service/load.go
  pkg/command/service/load_test.go
  pkg/config/config.go
Labels: size/L, approved, lgtm

#275 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#276 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#277 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#278 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#280 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#281 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#282 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
