Repository knative-extensions/kperf, pull requests merged in 2022-06, with the labels that each got.

#233 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#235 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#234 Scale from 0 to N using load test tool and Measure scale up latency
  README.md
  docs/service_load_replicas_latency.png
  pkg/command/service/load.go
  pkg/command/service/load_test.go
  pkg/command/service/service.go
  pkg/command/service/service_test.go
  pkg/types.go
Labels: size/XL, approved, lgtm, ok-to-test, kind/enhancement

#236 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#239 Fix lint error in code
  pkg/command/service/load.go
Labels: size/XS, approved, kind/cleanup, lgtm

#241 fix bugs in kperf load and docs
  docs/examples.md
  pkg/command/service/load.go
  pkg/command/service/load_test.go
Labels: approved, lgtm, ok-to-test, size/M

#242 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#243 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#244 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#246 Optimized kperf load and improved test coverage
  pkg/command/service/common.go
  pkg/command/service/load.go
  pkg/command/service/load_test.go
Labels: size/XL, approved, lgtm, ok-to-test

#247 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#248 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#249 add common functions to generate output and fix a bug
  pkg/command/service/common.go
  pkg/command/service/load.go
  pkg/command/service/measure.go
  pkg/command/service/scale.go
Labels: size/L, approved, lgtm, ok-to-test

#251 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M
