Repository knative-extensions/kperf, pull requests merged in 2022-02, with the labels that each got.

#180 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#182 Fix inconsistent vendoring issue
  go.mod
  go.sum
  vendor/github.com/kevinburke/go-bindata/.travis.yml
  vendor/github.com/kevinburke/go-bindata/AUTHORS.txt
  vendor/github.com/kevinburke/go-bindata/Makefile
  vendor/github.com/kevinburke/go-bindata/convert.go
  vendor/github.com/kevinburke/go-bindata/release.go
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/network/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: size/XL, approved, lgtm

#179 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: approved, lgtm, size/M

#181 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/network/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: size/XL, approved, lgtm

#184 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#185 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm

#186 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/url.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#189 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, approved, lgtm
