Repository knative-extensions/kperf, pull requests merged in 2022-07, with the labels that each got.

#252 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#253 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#255 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#256 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/influxdata/tdigest/LICENSE
  third_party/VENDOR-LICENSE/github.com/josharian/intern/license.md
  third_party/VENDOR-LICENSE/github.com/mailru/easyjson/LICENSE
  third_party/VENDOR-LICENSE/github.com/tsenart/vegeta/v12/lib/LICENSE
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#257 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#258 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#259 Fix image path bugs in docs
  docs/examples.md
Labels: size/XS, approved, lgtm, ok-to-test

#262 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#263 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#261 Support config file for kperf service generate
  core/root.go
  core/root_test.go
  docs/examples.md
  go.mod
  pkg/command/service/generate.go
  pkg/command/service/generate_test.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: size/L, approved, lgtm

#264 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, approved, lgtm

#265 fix golint errors: error strings should not end with punctuation or a newline
  pkg/command/service/common.go
  pkg/command/service/generate.go
  pkg/command/service/measure.go
  pkg/command/utils/util.go
Labels: approved, lgtm, size/S, ok-to-test

#266 pull in latest knative.dev/hack
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/L, approved, lgtm

#268 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#269 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/M
