Repository knative-extensions/kperf, pull requests merged in 2022-03, with the labels that each got.

#190 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#192 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#194 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: size/XS, approved, lgtm

#195 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/XL, approved, lgtm
