Repository knative-extensions/kperf, pull requests merged in 2022-05, with the labels that each got.

#215 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#213 Cleanup vendor owners files after build
  hack/build-funcs.sh
  hack/build.sh
Labels: approved, lgtm, size/S

#222 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#216 Add test for creating service from template
  pkg/command/service/generate.go
  pkg/command/service/generate_test.go
Labels: approved, lgtm, ok-to-test, size/M

#224 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#225 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#226 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#227 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#229 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#228 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  third_party/VENDOR-LICENSE/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/github.com/hashicorp/golang-lru/.gitignore
  vendor/github.com/hashicorp/golang-lru/2q.go
  vendor/github.com/hashicorp/golang-lru/README.md
  vendor/github.com/hashicorp/golang-lru/arc.go
  vendor/github.com/hashicorp/golang-lru/doc.go
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/networking/pkg/labels/labels.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm

#230 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/hashicorp/golang-lru/LICENSE
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: size/XL, approved, lgtm

#231 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/networking/pkg/labels/labels.go
  vendor/knative.dev/serving/pkg/networking/util.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm
