Repository knative-extensions/kperf, pull requests merged in 2022-11, with the labels that each got.

#316 fix style issues - goimports
  pkg/command/service/load.go
  pkg/command/service/load_test.go
  pkg/command/service/scale.go
  pkg/command/utils/htmltemplatebindata.go
  pkg/command/utils/util.go
  pkg/command/utils/util_test.go
  pkg/config/config_test.go
  pkg/perf_params.go
  pkg/types.go
Labels: approved, lgtm, size/M

#314 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, skip-review

#315 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#318 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#319 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: size/L, approved, lgtm

#322 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#323 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M
