Repository knative-extensions/kperf, pull requests merged in 2022-09, with the labels that each got.

#283 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#286 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, approved, lgtm

#287 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#292 fix bug in verifing external ip existence of loadbalancer
  pkg/command/service/scale.go
Labels: size/XS, approved, lgtm

#293 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#294 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#295 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#296 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#297 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#298 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
