Repository knative-extensions/kperf, pull requests merged in 2023-09, with the labels that each got.

#403 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#404 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#405 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#407 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#406 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#408 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/Dockerfile
  vendor/golang.org/x/net/http2/Makefile
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/text/unicode/norm/trie.go
  vendor/knative.dev/serving/AUTHORS
  vendor/modules.txt
Labels: size/L, approved, lgtm

#410 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#411 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#412 Prep for archive
  README.md
Labels: size/XS, approved, lgtm
